# Generated by Django 2.1.7 on 2019-03-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190317_2226'),
        ('utils', '0004_auto_20190319_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.Blog'),
            preserve_default=False,
        ),
    ]
