# Generated by Django 2.1.7 on 2019-03-14 15:16

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blogs.models.blog_thumbnail_event, verbose_name='博客缩略图'),
        ),
    ]
