# Generated by Django 2.1.7 on 2019-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190314_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pk'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='object_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogs.Tags'),
        ),
    ]
